[package]
name = "experimental-js-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
deno_core = "0.341.0"
deno_error = "0.5.6"
env = "1.0.1"
reqwest = "0.12.15"
tokio = { version = "1.44.1", features = ["full"] }
